use_frameworks!

platform :ios, '8.0'

target 'YBNSCache_Example' do
  pod 'YBNSCache', :path => '../'

  target 'YBNSCache_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
